import {
  BUILTIN_LAYOUT_CAPABILITIES,
  DiagnosticError,
  Drawing,
  EXCALIDRAW_API_URL,
  ExcalidrawApiClient,
  FONT,
  LAYERED_LAYOUT,
  LAYERED_LAYOUT_CAPABILITIES,
  MemoryFileSystem,
  RootedFileSystem,
  alignBounds,
  arrow,
  assertLayoutCapabilities,
  boundText,
  box,
  buildSemanticIR,
  card,
  collectLayoutRequirements,
  column,
  compile,
  connect,
  createLayoutAdapter,
  createMeasurer,
  createSceneGraph,
  createStyleResolver,
  diamond,
  distributeBounds,
  ellipse,
  endpointLabelBounds,
  expandDocument,
  fitTextSize,
  formatSceneResource,
  frame,
  heading,
  image,
  inset,
  lane,
  layoutWithAdapter,
  loadDocument,
  loadParsedDocument,
  measureRouteQuality,
  parse,
  parseSceneDocument,
  rectangle,
  renderScenePng,
  renderSceneSvg,
  resolveAssets,
  row,
  synchronizeEndpointLabels,
  text,
  tone,
  validateSemanticDocument,
  wrapText,
  writeDrawing,
  type LayoutAdapterDefinition,
} from "xdraw";
import { ExcalidrawApiClient as SubpathClient } from "xdraw/excalidraw-api";

const definition: LayoutAdapterDefinition = {
  name: "custom",
  capabilities: { ...BUILTIN_LAYOUT_CAPABILITIES, edgeRouting: true },
  layoutDocument: ({ options }) => ({ bottom: options.startY, routes: [] }),
};

const adapter = createLayoutAdapter(definition);

void [
  DiagnosticError, Drawing, EXCALIDRAW_API_URL, ExcalidrawApiClient, FONT, LAYERED_LAYOUT,
  LAYERED_LAYOUT_CAPABILITIES, MemoryFileSystem, RootedFileSystem, SubpathClient, adapter,
  alignBounds, arrow, assertLayoutCapabilities, boundText, box, buildSemanticIR, card,
  collectLayoutRequirements, column, compile, connect, createMeasurer, createSceneGraph,
  createStyleResolver, diamond, distributeBounds, ellipse, endpointLabelBounds, expandDocument,
  fitTextSize, formatSceneResource, frame, heading, image, inset, lane, layoutWithAdapter,
  loadDocument, loadParsedDocument, measureRouteQuality, parse, parseSceneDocument, rectangle,
  renderScenePng, renderSceneSvg, resolveAssets, row, synchronizeEndpointLabels, text, tone,
  validateSemanticDocument, wrapText, writeDrawing,
];
