import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as fontkit from "fontkit";

const FONT_ROOT = "node_modules/@excalidraw/excalidraw/dist/prod/fonts";
const families = {
  1: "Excalifont",
  2: "Nunito",
  3: "Cascadia",
};
const codePoints = Array.from({ length: 95 }, (_, index) => index + 32);

function sourceFont(directory: string): fontkit.Font {
  for (const filename of readdirSync(join(FONT_ROOT, directory)).sort()) {
    if (!filename.endsWith(".woff2")) continue;
    const font = fontkit.openSync(join(FONT_ROOT, directory, filename));
    if ("hasGlyphForCodePoint" in font
      && codePoints.every((codePoint) => font.hasGlyphForCodePoint(codePoint))) return font;
  }
  throw new Error(`No complete printable-ASCII font found for ${directory}`);
}

const target = "src/text/font-metrics.generated.ts";

export function generatedFileMatches(path: string, expected: string): boolean {
  try {
    return readFileSync(path, "utf8") === expected;
  } catch {
    return false;
  }
}

function generateSource(): string {
  const metrics = Object.fromEntries(Object.entries(families).map(([id, directory]) => {
    const font = sourceFont(directory);
    const advances = Object.fromEntries(codePoints.map((codePoint) => {
      const glyph = String.fromCodePoint(codePoint);
      return [glyph, Number((font.glyphForCodePoint(codePoint).advanceWidth / font.unitsPerEm).toFixed(6))];
    }));
    return [id, advances];
  }));
  return `// Generated by scripts/generate-font-metrics.ts.\nexport const FONT_ADVANCES: Readonly<Partial<Record<number, Readonly<Record<string, number>>>>> = ${JSON.stringify(metrics, null, 2)};\n`;
}

function main(): void {
  const output = generateSource();
  if (process.argv.includes("--check")) {
    if (!generatedFileMatches(target, output)) {
      console.error(`${target} is stale; run npm run generate:font-metrics`);
      process.exitCode = 1;
    }
  } else {
    writeFileSync(target, output, "utf8");
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
