export const MAX_CODE_SOURCE_CHARACTERS = 100_000;
export const MAX_CODE_LINES = 2_000;
export const MAX_CODE_LINE_CHARACTERS = 10_000;

export const MAX_HIGHLIGHT_SOURCE_CHARACTERS = 20_000;
export const MAX_HIGHLIGHT_LINES = 80;
export const MAX_HIGHLIGHT_LINE_CHARACTERS = 2_000;
export const MAX_HIGHLIGHT_RUNS = 240;
export const MAX_DRAWING_HIGHLIGHT_RUNS = 800;
